### ISSUE TITLE
Code for model calibration

### ISSUE THREAD

**Issue by Cheeun** [Xiuyu-Li/q-diffusion#10]
Hello, 
I am curious if there are any plans to share your code for model calibration.
(Code for obtaining the quantized model checkpoints)
Btw, thanks for sharing your code! Your work is cool!

**Comment by Xiuyu-Li** [comment]
Hi, Thank you for your interest in our work! We're currently prioritizing the development of our end-to-end quantization implementation, and thus the refinement and release of the model calibration code will follow accordingly. At this point, we can't specify a timeline for its release, but we will try to get it done in the following few weeks. We appreciate your understanding and patience. 

Just a side note, since our calibration process is quite simple with the key idea being sampling the whole time steps distribution uniformly, you can also try replicating this part by creating the calibration dataset based on our algorithm 1 in the paper and referencing this [codebase](https://github.com/yhhhli/BRECQ).

**Comment by Cheeun** [comment]
Thanks for your detailed answer! While waiting for the release, I will try reproducing it with your reference!

**Comment by arthursunbao** [comment]
+1, looking forward for the release of model calibration code :)

**Comment by hanhanpp** [comment]
waiting for the new release of calibraiton methods !
